### ISSUE TITLE
Error gan

### ISSUE THREAD

**Issue by jordiyapz** [zevtyardt/lk21#2]
Error gan pas ngejalanin `lk21` di cmd.

```
Traceback (most recent call last):
  File "[...]\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "[...]\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "[...]\lk21.exe\__main__.py", line 4, in <module>
  File "[...]\lk21\__init__.py", line 6, in <module>
    from .lk21 import main
  [...]\lk21\lk21.py", line 69
    if (name := soup.find(class_="package-header__name")):
                 ^
SyntaxError: invalid syntax
```

Typo sintaksnya yah?

> Spesifikasi
> OS: Windows 10
> Python: 3.7.3
> lk21: 1.5.28

**Comment by zevtyardt** [comment]
Minimal versi python sudah saya set untuk `3.8` keatas gan. Soalnya walrus operator baru tersedia di python3.8 keatas. Pertanyaannya bagaimana agan bisa menginstall di python versi 3.8 kebawah

**Comment by jordiyapz** [comment]
Ohh oke, gan. Thanks. Baru tau ternyata ada operator walrus di python
